### PR TITLE
Merging Development to Main

### PR DESCRIPTION
**Pull request by rosiemaguire**
- Skill post requests
- cv field changing to github_profile field in CustomUser model
- Staff able to create new staff users
- Staff able to update all user fields
- New has_mentored field in CustomUser model
- Adding check for if mentor has onboarding_status of "Ready" before allowing them to register for events
- Preventing duplicate registrations for mentor events
- Adding current user view
- Mentors able to update their availability against events they are registered for

### CODE REVIEW

**Comment by rosiemaguire** [comment]
token auth [POST]
http://127.0.0.1:8000/api-token-auth/
```
{
	"username":"admin",
	"password":"admin"
}
```

users [GET] [POST] # GET can only show own user unless staff. Restrictions around what fields can be submitted on user creation unless staff
http://127.0.0.1:8000/users/
```
{
	"username": "test",
	"first_name": "hello",
	"last_name": "hello",
	"password": "test",
	"email": "test@test.com",
	"mobile": "0000000000",
	"location": "Brisbane",
	"github_profile": "https://wwww.test.com/",
	"has_mentored": true,
	"skills": [
		"Python"
	]
}
```
one user [GET] [PUT] #only own user unless staff
http://127.0.0.1:8000/users/<id>/
```
{
	"skills": ["JavaScript"],
	"github_profile": "https://www.test.com/"
}
```
#PUT REQUEST MUST INCLUDE SKILLS #

user profile [GET]
http://127.0.0.1:8000/users/self/

mentor events [GET][POST]
http://127.0.0.1:8000/mentor-events/
```
{
	"event_id": 15,
	"mentor_id": 2
}
``` 
# mentor_id is only required if making POST request as staff user #

skills [GET] [POST]
http://127.0.0.1:8000/users/skills/
{
	"name": "Python"
}
events [GET][POST]
http://127.0.0.1:8000/events/
```
{
	"title":"Event One",
	"start_date":"2023-10-10",
	"end_date":"2023-10-11",
	"location":"Brisbane",
	"is_published": "true"
}
```

events [PUT]
http://127.0.0.1:8000/events/<id>/
```
{
	"is_published": false
}
```

**Review by Andrea-Rivera — APPROVED** [review]
All is ok

**Review by oriyannadav — COMMENTED** [review]
everything works but the mentor events and the PUT request for users :)

**Comment by rosiemaguire** [comment]
PUT request for users must include skills. 
What doesn't work for mentors-events?
@mayadomi are you able to check these ones please?

**Comment by mayadomi** [comment]
Will have a look now 😄

**Review by mayadomi — CHANGES_REQUESTED** [review]
- Skill post requests -- WORKS
- cv field changing to github_profile field in CustomUser model -- WORKS, can read/write it
- Staff able to create new staff users -- PARTIAL - is_staff=validated_data.get('is_staff') needs to be in the CustomStaffSerializer, without it seems to default back to false.
- Staff able to update all user fields -- WORKS
- New has_mentored field in CustomUser model -- WORKS, can read/write
- Adding check for if mentor has onboarding_status of "Ready" before allowing them to register for events -- WORKS
- Preventing duplicate registrations for mentor events -- WORKS
- Adding current user view - WORKS (assuming this is the 'users/self/' url?
- Mentors able to update their availability against events they are registered for -- WORKS

**Review by mayadomi — APPROVED** [review]
Works perfectly 🥰

**Pull request merged**
